sudo: required

services:
  - docker

env:
  global:
  - DOCKER_REPO=sareyes/fsharp-example
  - secure: UX7Yh2bJxeXJIBK0/NfQkLMQQx5asEWehNBnXI5/uxYP6ykQhFTUWVwE05fD/SLL0A0h5AU0ILEdI7PSQWZ5fDgOqKOQ4OHeCZq+JBlglobLmJVNI+Hvt8HE7FqjHaK9GVYTXGFFsOCEyCVl7Lqps27nWFjRSc0/F8kUXPd45rwU1XEBnSEeJuZ2i7WTkWMoluBZBGgH34pjBk8mEETefXq+rlqo1uD09tmGC/BCWlFqBMaPPXfEX/0yaB5rE3eAn5Afxfe0cDw082j+2vWtu6F83ryGus6/hCR87bRF1z4E4MOVMLCCH2x9/JcaPJkVkqYT+fUmJWemcDnWbdEAnhhJt714rNPEfrdB6+DcN1k8LFRPR5VusWezIzm+4byNi70eP1cXQXfpRNexrPc0IE8KruNLN0pTZAfVyj8CFrf6JeN45CLhDuTynauuNGgJThUnfJtL5ZBgjZvEaPGEsx6YSeAC3UrqMPqEbafNkR/APvxaQvjN1DljBGfc91TT80oaY41k1DQXJZRuf/xSECn1Qi8VTqgUf+NLXCI8nPQivbCt63YfbfZ2cx/Cz7DRHFjSu72j0W9oCByGgBEU0jYqlIsVuKh33DQ6uB+qRe1MZ3XjYEj2ue/LqO/yakxgksHns+re5DWL36DwmTO+1sdlWti1UcOw3YLqyku4iec=
  - secure: UEcLOuaWn+q5qUHiqMUc95PupKVBDlXTDR46COsOdFFVovalm2/q2rlvwLLITatYhUx66itVFLwKHbmeL9EisOzq3vYLAZzdiCfW9cmw819+MqsKXulHlukJCq8D6Z0IHs8x2sf50Djm3tuoXvUuIpb039Am3KxyleuAon+Prc80Dv0dRqQA9zhSuOTVOaj2/A5gTwb0yzFT4jyxq/xlYHmlBZeT7S7TsfZ32VakhnIXWaT0vNIQ5sOG/svQh/1FMkxElN5+xrJGaQL6YtZnxFVzDt41ufxV6aqhEQoG6T7l/qUdt/IDYjrsmePiz3XEAYSabvW8M1Qf03h7kF2vi7x0ekHqqIZEsbyAxo9GKl8Oe/BcK+RZlHVk56f3kp4vA5fn60wT5hirp50M9qSNsGpnmoG/tX0TPqqyTndTOSOKvs8DPloMVhOa7za6ApD8S8y4//Zn9SRS9fRXN9HTgIKGKeVjofMjEeH6mFquGEZOrbidGRLQ8DdEWP96M1OgDzCo+M431yiqmi4KHSrdbuaZi3O5ADpfKnS/h4OsLWWMEDhkerPKRs1c18w7EyYcvRlTm8wbzMToF3goHc2kAIygxyzceVDo0H6iJq+aBWU6e1gCvOZdnqJtf/eBO6yAQjuREgvjx3F25DX0rijOmNu81hj32a8U+OMyBVkznyw=
before_install:
  - echo '{"experimental":"enabled"}' | sudo tee $HOME/.docker/config.json
  - sudo service docker start
install:
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
script:
  - bash ci.sh
